# Generated by Django 5.0.6 on 2024-06-14 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_dept_alter_employee_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_role',
            name='empl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
    ]
