# Generated by Django 5.0.6 on 2024-06-14 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_role_empl'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_dept',
            name='empl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employee_dept',
            name='dept',
            field=models.CharField(choices=[('SALES', 'SALES'), ('RND', 'RND'), ('HR', 'HR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_role',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'MANAGER'), ('SUPERVISOR', 'SUPERVISOR'), ('ASSISTANT MANAGER', 'ASSISTANT MANAGER')], max_length=100, null=True),
        ),
    ]
